agent:
  interval_secs: 10
  log_level: "info"
  host_name: "<hostname>"

otlp:
  endpoint: "<url>"
  timeout_secs: 5

collectors:
  temperature:
    enabled: true
  iptables:
    enabled: true
    command: "iptables-save -c"
    # 1. Собирать ли итоговую статистику по цепочкам (policy counters)
    collect_chain_totals: true

    # 2. Фильтрация правил (все поля опциональны, по умолчанию собирается ВСЁ)
    # Если оставить пустым [], будут собираться вообще все действия (ACCEPT, DROP, REJECT и т.д.)
    target_filter: [] # Пример: ["DROP", "REJECT"] — если нужны только блокировки

    # Жёсткий режим: собирать только с комментариями/сетами (по умолчанию false!)
    only_with_metadata: false

    # Игнорировать служебные цепочки Docker, если они создают слишком много шума
    ignore_chains: ["DOCKER-ISOLATION-STAGE-1", "DOCKER-ISOLATION-STAGE-2"]
  process:
    enabled: true
    # 1. Фильтры процессов (если include_processes пуст — собираются все)
    include_processes: []
    exclude_processes: ["kworker/*"]

    # 2. Фильтр по systemd units (если пуст — определяются автоматически для всех процессов)
    track_systemd_units: []

    # 3. Дополнительные метрики
    collect_io: true
    collect_fds: true

    # 4. Пороги отсечения "шумных" мелких процессов
    min_cpu_percent: 0.0
    min_memory_mb: 0
  filesystem:
      enabled: true
      ignore_mount_points:
        - /proc
        - /sys
        - /dev
        - /run
        - /snap
      include_overlay: true     # ← только для overlayfs-корня
      ignore_fs_types:          # ← overlay убрать из списка
        - tmpfs
        - devtmpfs
        - squashfs
  disk:
      enabled: true
      ignore_device_mapper: true    # Игнорировать LVM (dm-0, dm-1)
      ignore_devices: []            # Пример: ["sr0"] для CD-ROM
      collect_io: true              # Собирать read/write counters
  network:
      enabled: true
      ignore_interfaces:
        - lo
        - veth
        - docker
        - br-
        - virbr
        - tun
        - tap
        - wg
      ignore_exact: []
      collect_ip: true
