use otlp_sys_agent::collectors::iptables::parse_iptables_save;
use otlp_sys_agent::config::IptablesCollectorConfig;

fn mock_iptables_output() -> &'static str {
    r#"# Generated by iptables-save v1.8.10
*filter
:INPUT ACCEPT [10500:8450120]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [500:30000]
:DOCKER-USER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
[150:12000] -A INPUT -p tcp -m tcp --dport 22 -m set --match-set crowdsec-blacklists src -m comment --comment "block bad ips" -j DROP
[42:2400] -A DOCKER-USER -m comment --comment "allow web traffic" -j ACCEPT
[10:500] -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
[5:250] -A DOCKER-ISOLATION-STAGE-1 -j DROP
COMMIT
*nat
:PREROUTING ACCEPT [100:5000]
COMMIT
"#
}

#[test]
fn test_parse_chain_totals() {
    let config = IptablesCollectorConfig {
        enabled: true,
        command: "sudo iptables-save -c".to_string(),
        collect_chain_totals: true,
        target_filter: vec![],
        only_with_metadata: false,
        ignore_chains: vec![],
    };

    let dump = parse_iptables_save(mock_iptables_output(), &config);

    assert_eq!(dump.chain_totals.len(), 6);
    assert_eq!(dump.chain_totals[0].chain, "INPUT");
    assert_eq!(dump.chain_totals[0].policy, "ACCEPT");
    assert_eq!(dump.chain_totals[0].packets, 10500);
    assert_eq!(dump.chain_totals[0].bytes, 8450120);
}

#[test]
fn test_parse_rules_with_metadata() {
    let config = IptablesCollectorConfig {
        enabled: true,
        command: "sudo iptables-save -c".to_string(),
        collect_chain_totals: false,
        target_filter: vec![],
        only_with_metadata: false,
        ignore_chains: vec![],
    };

    let dump = parse_iptables_save(mock_iptables_output(), &config);

    assert_eq!(dump.rules.len(), 4);

    let r0 = &dump.rules[0];
    assert_eq!(r0.table, "filter");
    assert_eq!(r0.chain, "INPUT");
    assert_eq!(r0.packets, 150);
    assert_eq!(r0.bytes, 12000);
    assert_eq!(r0.target.as_deref(), Some("DROP"));
    assert_eq!(r0.match_set.as_deref(), Some("crowdsec-blacklists"));
    assert_eq!(r0.match_comment.as_deref(), Some("block bad ips"));
    assert_eq!(r0.proto.as_deref(), Some("tcp"));
    assert_eq!(r0.dport.as_deref(), Some("22"));

    let r1 = &dump.rules[1];
    assert_eq!(r1.chain, "DOCKER-USER");
    assert_eq!(r1.match_comment.as_deref(), Some("allow web traffic"));
}

#[test]
fn test_filtering_options() {
    let config = IptablesCollectorConfig {
        enabled: true,
        command: "sudo iptables-save -c".to_string(),
        collect_chain_totals: true,
        target_filter: vec!["DROP".to_string()],
        only_with_metadata: true,
        ignore_chains: vec!["DOCKER-ISOLATION-STAGE-1".to_string()],
    };

    let dump = parse_iptables_save(mock_iptables_output(), &config);

    assert!(dump
        .chain_totals
        .iter()
        .all(|c| c.chain != "DOCKER-ISOLATION-STAGE-1"));
    assert_eq!(dump.rules.len(), 1);
    assert_eq!(dump.rules[0].chain, "INPUT");
    assert_eq!(dump.rules[0].target.as_deref(), Some("DROP"));
}
